### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by luncliff** [OliveOld/PetsDroid#1]
### 빌드 실패/오류 관련 이슈

**Comment by luncliff** [comment]
### Resource
오류보고를 보면 drawable쪽에서 이미지를 찾지 못한다고 나오는데, 아마 git에 추가(add)되지 않은게 아닌가 싶습니다. 확인 부탁드립니다.

### API Version
현재 빌드를 API 23 (6.0)으로 시도하고 있는데, 혹시 다른 버전(4.4)에 맞춰야 하는지요?

**Comment by 0n33y3d-z0mb13** [comment]
죄송합니다 지금 확인했네요
1. 파일 빠진것 다시 올렸습니다
2. 컴파일 버전 및 최소 sdk는 readme 파일대로 하시면 됩니다

**Comment by luncliff** [comment]
곧 Branch 통합 문제가 해결되고 Policy가 결정되면 이 이슈는 닫겠습니다.

현재는 빌드 불가능 상태이므로 현상태를 유지하고, 관련 이슈를 별도로 개설하겠습니다.
