### ISSUE TITLE
merge 하는 방법

### ISSUE THREAD

**Issue by seobink** [OliveOld/PetsDroid#13]
1. github 통해서 commit을 한다.
2. git cmd 창 연다
2-1. git pull 입력
3. git checkout master  입력
4. git merge 브렌치이름  입력
   (그럼 충돌 목록 뜬다)
 *충돌난 부분 경로 보고 싶으면 git status 입력
5. 안스 켜서 충돌난 부분 수정하기
6. git add 출동난부분경로 (혹은 git add *)  입력
7. git commit  입력
8. git push  입력

끝

**Comment by 0n33y3d-z0mb13** [comment]
이러렇게 했는데 왜!!! 가지가 없어지는 것이지?

**Comment by 0n33y3d-z0mb13** [comment]
어쨌든 수고하셨습니다!!!!굿굿
