### ISSUE TITLE
Realm: Database

### ISSUE THREAD

**Issue by 0n33y3d-z0mb13** [OliveOld/PetsDroid#5]
사용법은 해당 페이지 참조: http://dktfrmaster.blogspot.kr/2016/10/orm-realm.html

**Comment by 0n33y3d-z0mb13** [comment]
현재 데이터베이스 모습
![database](https://cloud.githubusercontent.com/assets/21700941/24081312/bd2d3b18-0cf4-11e7-81e8-5bce5ad10a43.PNG)

**Comment by seobink** [comment]
Q : 데이터 베이스 구조가 바뀌는 거죠?? piechart 세가지(가만히, 뛰기, 걷기)로 출력되게 조정해놨는데 그렇게 하면 되죠??

**Comment by 0n33y3d-z0mb13** [comment]
1. DogProfile : 강아지 프로필로서 해당 강아지의 기본 프로필 뿐만 아니라 측정한 값들을 가진다
```
    @PrimaryKey
    private int dog_id;
    private String dog_name;
    private int dog_age;
    private String dog_sex;
    private String dog_photo;
    private PostureData posture_data;
```

2. PostureData : 해당 날짜에 받아온 자세 측정 값들. 4가지의 자세를 가진다.
```
    @PrimaryKey
    private int data_id;           // 각 데이터가 갖는 기본 id
    private String date;            // 데이터 측정 된 시간 저장
    private double lie_time;
    private double stand_time;
    private double walk_time;
    private double run_time;
```

+ BleData :  나중에 가능하면 블루투스 빈들을 선택할 수 있는 리스트를 출력하기 위한 오브젝트
```
    @PrimaryKey
    private String BT_Address; // BT device MAC address
    private String BT_name; // device BT name
    private int rssi; // signal strength at scan
    private boolean isSelected; // selected by user
```

@seobink 
❓ 
강아지와 매일 날짜에 따라 저장되는 데이터들은 일대 다의 관계인지..? 같이 생각 해 주세요
❗️ 
일단은 Light Blue Bean에서 값을 보내면 PostureData라는 오브젝트로 저장이 될 것입니다.  나중에 Pie Chart에서 Realm Object를 가져와 쓰려면 해당 오브젝트로부터 값을 불러오면 될 것 같습니다. 알고리즘이 충분히 완성 되면 lie_time과 stand_time이 서로 구분 될 것인지도 결정이 될 것 같아 보입니다.
