### ISSUE TITLE
진행 사항 및 예정

### ISSUE THREAD

**Issue by 0n33y3d-z0mb13** [OliveOld/PetsDroid#7]

**Comment by 0n33y3d-z0mb13** [comment]
# 1순위
- [x] DB 생성
- [x] fake 정보 DB에 저장 해 보기 -> myDog.setPostureData(1, "2017-04-17", 36000, 40000, 20000, 10000);
- [x] 메인 슬라이딩 바 아래와 같이 수정
- [x] 각 액티비티도 아래에 맞게 수정해야 함
- [x]  강아지 프로필 추가, 삭제, 수정 시 메인 화면에서 리프레시 해줘야함
- [x] 튜토리얼 부분에서 강아지 크기 있으므로 프로필 DB에 이부분 넣어야함, 그리고 선택 시 다음 액티비티로 넘겨서 프로필 작성시 같이 저장하도록 함
- [x] 새 강아지 추가 시 튜토리얼 부분으로 넘어가게...
- [x] 강아지 여러 마리 일 경우 구분법/ 각자 프로필 수정 및 생성부분 추가 => 처음 기기 켰을 때 튜토리얼 부분에서 강아지 프로필 및 DB(dog_id =1) 생성 
- [x] 기기 목록 출력 > 코드 그냥 복붙 ㄱㄱ(Branch: Bluetooth - documents>issue에 올린 url 참고)
- [x] 강아지 관리 탭에서 수정 및 등록할 강아지 관리 탭을 추가. 나의 강아지 보기 해서 DogProfile를 리스트로 강아지들 쭉 보여줘야 함. 그리고 눌렀을 때 강아지 프로필이랑 측정한 날 수 등을 보이게 하고 수정, 삭제를 누를 수 있어야 한다. 
- [x] Piechart와 realm 연결하여 fake data 출력
----------
- [ ]  위에서 아직 측정한 데이터의 수 보이기 안했음
- [x] 강아지 프로필 추가,수정,삭제 시 posture data list 연결해야함
- [x] 블루투스연결하는 부분 좀 더 한눈에 들어오도록 레이아웃 바꿈. 원형 프로그레스 등 넣기

**Comment by 0n33y3d-z0mb13** [comment]
# 2순위(UI)
- [x] 슬라이딩 바 모든 액티비티에서 열리도록 
- [x] 액티비티 쌓이는 것 해결
- [x] 색상 통일
- [x] 슬라이딩 바 글씨 앞에 작은 아이콘 넣어주세요
- [x] 슬라이딩 바 색상 통일 부탁드립니다
- [x] 액션 바 색상 바꾸거나 없애야 할 곳은 없애기
--------
- [x] 메인>현재 강아지 정보 작게, 파이 차트 크게, 오늘의 멘트
- [x] 드로어 토글 버튼 만들기
- [ ] 메인 액티비티 돌아올 때 드로어 닫히게 하기
- [x] 액티비티 이동 애니메이션 없애기(????-서빈)

**Comment by 0n33y3d-z0mb13** [comment]
# (나아중에)
- [ ] 변수명 함수명 등 통일
- [ ] 나중에 가능하면 최근의 활동량을 histogram로 보여주도록 하는 괜찮을 듯(걷기, 달리기 부분만)

**Comment by 0n33y3d-z0mb13** [comment]
BluetoothActivity.java
블루투스 연결
시리얼 통신
DB 저장 > 현재 fake 값 myDog.setPostureData(1, "2017-04-17", 36000, 40000, 20000, 10000); 하나 넣음
블루투스 연결 해제

**Comment by seobink** [comment]
# (가능하면)
- [x] piechart 메인/데일리 모두 코드 들어가 있는데, .java 파일로 추출해서 연동할지 아니면 그냥 각각 넣는 것이 좋을지 비교해보기
- [x] DB 데이터 불러오는 함수 만들기

**Comment by 0n33y3d-z0mb13** [comment]
5/23 

- [x] MyDialogFragment , res>layout>menu.xml 사용 확인 후 제거 좀 부탁드립니다.

07/5/25 서빈
내가 지우면 잘 못 지울 것 같애서
menu에 필요없는거 다 지워도 될듯요 ...
안쓰는거 빼고 다 삭제 ㄱㄱ 사용하는 부분은 없슴

5/25
그럼 마지막에 정리하는걸로~ 일단 에러만 수정하고 마스터 갱신했음

**Comment by 0n33y3d-z0mb13** [comment]
5/26~5/28
<김민지 해야 할 일>
- [x] 블루투스  안 켰을 시 키라는 다이얼로그 출력
- [x] 메인에 프로필 출력 안되는 경우 있음
- [ ] 강아지 DB와 posture DB 연결해야 함
- [x] 트레이닝 부분에 블루투스 부분 넣기
<img src="https://cloud.githubusercontent.com/assets/21700941/26509287/0c0a12aa-4293-11e7-9cd1-fa5f410e0dda.png" width="300px;"/>

<김서빈씨 수정 부탁드립니다>
- [x] 트레이닝 액티비티에서 디자인 에러 발생했는데 확인부탁!
<img src="https://cloud.githubusercontent.com/assets/21700941/26448952/c093a970-418a-11e7-9a60-163dd2eeb008.png" width="300px;"/>
- [ ] 파이 차트 아직 안 받아왔을 경우 데이터를 아직 받지 않았다는 문구만 출력하도록 부탁드립니다

**Comment by seobink** [comment]
- [x] 강아지 프로필 오류처리 : 사진 안 넣었을 경우 오류 처리

**Comment by 0n33y3d-z0mb13** [comment]
서빈씨 mainactivity에서
pie chart의 데이터를 읽어오는 부분을 함수로 만들어서
Oncreate시 한번 호출, onResume에서 한번 호출할 수 있도록 변경 부탁드립니다
액티비티에 다시 접근 했을 때 파이 차트가 다시 그려져야돼서 그래요

**Comment by 0n33y3d-z0mb13** [comment]
- [x] 트레이닝 액티비티에서 빈에 연결하는동안은 버튼들 숨기고 progress나타내기

**Comment by seobink** [comment]
@everlong1992 넵 반영하겠습니다
